name: prek-action
description: run prek, a pre-commit action
inputs:
  extra_args:
    description:
    required: false
    default: '--all-files'
runs:
  using: composite
  steps:
    - name: Install prek
      shell: bash
      run: |
        python -m pip install prek

    - uses: actions/cache/restore@v4
      id: cache
      with:
        path: ~/.cache/prek
        key: prek|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install hooks
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
        # todo(onerandomusername): find this bug and pr it upstream
      run: |
        prek install-hooks
        rm -rf ~/.cache/prek/hooks/pygrep-*

    - name: Save cache
      uses: actions/cache/save@v4
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      with:
        path: ~/.cache/prek
        key: prek|${{ hashFiles('.pre-commit-config.yaml') }}

    - run: prek run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
      shell: bash
branding:
  icon: git-commit
  color: orange
